### ISSUE TITLE
Main class being named main.

### ISSUE THREAD

**Issue by n-tdi** [Hutch79/F-Command#3]
It's terrible practice to name your Main class "Main“ as it doesn't help developers and users look at the console and figure out what plug-in is causing errors or issues in the console! It's super important especially for public plug-ins to name your main class ANYTHING that relates to your project. For you I would rename your Main class to `FCommand` as that is what you're project revolves around. 

Please read this for more information. https://www.spigotmc.org/threads/why-you-shouldnt-name-your-main-plugin-class-main.493289/

**Comment by Hutch79** [comment]
Thanks for your feedback!
I just renamed the Main class.

If you've seen nothing else, I would love a review on [SpigotMC](https://www.spigotmc.org/resources/f-command.108009/reviews).

**Comment by n-tdi** [comment]
Haha, I'll keep looking for now.
